### ISSUE TITLE
[epic] Implement replay recorder

### ISSUE THREAD

**Issue by Feodor0090** [Feodor0090/nmania#15]
- [ ] Decide on 0-allocation storage model
- [ ] Implement recorder
- [ ] Implement OSR encoder

**Comment by Feodor0090** [comment]
Subtasks:

- [ ] Add way to get beatmap's md5
- [ ] Add auto difficulty search based on md5
- [ ] Encode md5 to replay
- [ ] Calculate OSR's aacuracy
- [ ] Reliablity pass

**Comment by Feodor0090** [comment]
Mainly functionable. Dropping.
