### ISSUE TITLE
[epic] Rich skinning

### ISSUE THREAD

**Issue by Feodor0090** [Feodor0090/nmania#8]
### Support

- [x] A class for rich skin object
- [x] Info screen with tutorial

### Elements

- [x] Notes
- [x] Hold heads
- [x] Keyboard
- [x] Score&acc counters
- [x] Judgments 
- [ ] Pass/fail splashes 
- [ ] Combo splash
- [ ] Pause menu buttons
