### ISSUE TITLE
[epic] Move all game's interface from LCDUI

### ISSUE THREAD

**Issue by Feodor0090** [Feodor0090/nmania#9]
- [x] Info menu
- [ ] Info subscreens with text
- [x] BMSs list
- [x] BMS page
- [x] Player loader
- [ ] Error message that there are no BMSs
- [x] Replay selector
- [x] Error messages during beatmap loading

**Comment by Feodor0090** [comment]
Not a blocker.

**Comment by Feodor0090** [comment]
This should be implemented similar to vika touch screen system. Of course, in more sane way
